configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "setupmobans/templates"
  - ".moban.d"
  configuration: pyecharts-snapshot.yml
targets:
  - setup.py: setup.py
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - test.sh: test.sh.jj2
